app:
  name: bugtracktor
  user_cookie: c_user
#  populate_db: "${POPULATE_DB}"
#  reset_db: "${POPULATE_DB}"

jwt:
  header: Authorization
  expires_in: 31540000 # 1 year
  secret: tracktor
  cookie: AUTH-TOKEN